/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as publicauthRouteRouteImport } from './routes/(public)/(auth)/route'
import { Route as protectedadminRouteRouteImport } from './routes/(protected)/(admin)/route'
import { Route as publicWhoAreWeIndexRouteImport } from './routes/(public)/whoAreWe/index'
import { Route as publicPollIndexRouteImport } from './routes/(public)/poll/index'
import { Route as publichomeIndexRouteImport } from './routes/(public)/(home)/index'
import { Route as publicauthUpdatePasswordIndexRouteImport } from './routes/(public)/(auth)/update-password/index'
import { Route as publicauthSignUpIndexRouteImport } from './routes/(public)/(auth)/sign-up/index'
import { Route as publicauthLoginIndexRouteImport } from './routes/(public)/(auth)/login/index'
import { Route as publicauthForgotPasswordIndexRouteImport } from './routes/(public)/(auth)/forgot-password/index'
import { Route as protectedadminHomePageDataIndexRouteImport } from './routes/(protected)/(admin)/home-page-data/index'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicauthRouteRoute = publicauthRouteRouteImport.update({
  id: '/(public)/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedadminRouteRoute = protectedadminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => protectedRouteRoute,
} as any)
const publicWhoAreWeIndexRoute = publicWhoAreWeIndexRouteImport.update({
  id: '/(public)/whoAreWe/',
  path: '/whoAreWe/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicPollIndexRoute = publicPollIndexRouteImport.update({
  id: '/(public)/poll/',
  path: '/poll/',
  getParentRoute: () => rootRouteImport,
} as any)
const publichomeIndexRoute = publichomeIndexRouteImport.update({
  id: '/(public)/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicauthUpdatePasswordIndexRoute =
  publicauthUpdatePasswordIndexRouteImport.update({
    id: '/update-password/',
    path: '/update-password/',
    getParentRoute: () => publicauthRouteRoute,
  } as any)
const publicauthSignUpIndexRoute = publicauthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => publicauthRouteRoute,
} as any)
const publicauthLoginIndexRoute = publicauthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => publicauthRouteRoute,
} as any)
const publicauthForgotPasswordIndexRoute =
  publicauthForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => publicauthRouteRoute,
  } as any)
const protectedadminHomePageDataIndexRoute =
  protectedadminHomePageDataIndexRouteImport.update({
    id: '/home-page-data/',
    path: '/home-page-data/',
    getParentRoute: () => protectedadminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publichomeIndexRoute
  '/poll/': typeof publicPollIndexRoute
  '/whoAreWe/': typeof publicWhoAreWeIndexRoute
  '/home-page-data/': typeof protectedadminHomePageDataIndexRoute
  '/forgot-password/': typeof publicauthForgotPasswordIndexRoute
  '/login/': typeof publicauthLoginIndexRoute
  '/sign-up/': typeof publicauthSignUpIndexRoute
  '/update-password/': typeof publicauthUpdatePasswordIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publichomeIndexRoute
  '/poll': typeof publicPollIndexRoute
  '/whoAreWe': typeof publicWhoAreWeIndexRoute
  '/home-page-data': typeof protectedadminHomePageDataIndexRoute
  '/forgot-password': typeof publicauthForgotPasswordIndexRoute
  '/login': typeof publicauthLoginIndexRoute
  '/sign-up': typeof publicauthSignUpIndexRoute
  '/update-password': typeof publicauthUpdatePasswordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(protected)/(admin)': typeof protectedadminRouteRouteWithChildren
  '/(public)/(auth)': typeof publicauthRouteRouteWithChildren
  '/(public)/(home)/': typeof publichomeIndexRoute
  '/(public)/poll/': typeof publicPollIndexRoute
  '/(public)/whoAreWe/': typeof publicWhoAreWeIndexRoute
  '/(protected)/(admin)/home-page-data/': typeof protectedadminHomePageDataIndexRoute
  '/(public)/(auth)/forgot-password/': typeof publicauthForgotPasswordIndexRoute
  '/(public)/(auth)/login/': typeof publicauthLoginIndexRoute
  '/(public)/(auth)/sign-up/': typeof publicauthSignUpIndexRoute
  '/(public)/(auth)/update-password/': typeof publicauthUpdatePasswordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/poll/'
    | '/whoAreWe/'
    | '/home-page-data/'
    | '/forgot-password/'
    | '/login/'
    | '/sign-up/'
    | '/update-password/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/poll'
    | '/whoAreWe'
    | '/home-page-data'
    | '/forgot-password'
    | '/login'
    | '/sign-up'
    | '/update-password'
  id:
    | '__root__'
    | '/(protected)'
    | '/(protected)/(admin)'
    | '/(public)/(auth)'
    | '/(public)/(home)/'
    | '/(public)/poll/'
    | '/(public)/whoAreWe/'
    | '/(protected)/(admin)/home-page-data/'
    | '/(public)/(auth)/forgot-password/'
    | '/(public)/(auth)/login/'
    | '/(public)/(auth)/sign-up/'
    | '/(public)/(auth)/update-password/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  publicauthRouteRoute: typeof publicauthRouteRouteWithChildren
  publichomeIndexRoute: typeof publichomeIndexRoute
  publicPollIndexRoute: typeof publicPollIndexRoute
  publicWhoAreWeIndexRoute: typeof publicWhoAreWeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)': {
      id: '/(public)/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/(admin)': {
      id: '/(protected)/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedadminRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(public)/whoAreWe/': {
      id: '/(public)/whoAreWe/'
      path: '/whoAreWe'
      fullPath: '/whoAreWe/'
      preLoaderRoute: typeof publicWhoAreWeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/poll/': {
      id: '/(public)/poll/'
      path: '/poll'
      fullPath: '/poll/'
      preLoaderRoute: typeof publicPollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(home)/': {
      id: '/(public)/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publichomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/(auth)/update-password/': {
      id: '/(public)/(auth)/update-password/'
      path: '/update-password'
      fullPath: '/update-password/'
      preLoaderRoute: typeof publicauthUpdatePasswordIndexRouteImport
      parentRoute: typeof publicauthRouteRoute
    }
    '/(public)/(auth)/sign-up/': {
      id: '/(public)/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof publicauthSignUpIndexRouteImport
      parentRoute: typeof publicauthRouteRoute
    }
    '/(public)/(auth)/login/': {
      id: '/(public)/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof publicauthLoginIndexRouteImport
      parentRoute: typeof publicauthRouteRoute
    }
    '/(public)/(auth)/forgot-password/': {
      id: '/(public)/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof publicauthForgotPasswordIndexRouteImport
      parentRoute: typeof publicauthRouteRoute
    }
    '/(protected)/(admin)/home-page-data/': {
      id: '/(protected)/(admin)/home-page-data/'
      path: '/home-page-data'
      fullPath: '/home-page-data/'
      preLoaderRoute: typeof protectedadminHomePageDataIndexRouteImport
      parentRoute: typeof protectedadminRouteRoute
    }
  }
}

interface protectedadminRouteRouteChildren {
  protectedadminHomePageDataIndexRoute: typeof protectedadminHomePageDataIndexRoute
}

const protectedadminRouteRouteChildren: protectedadminRouteRouteChildren = {
  protectedadminHomePageDataIndexRoute: protectedadminHomePageDataIndexRoute,
}

const protectedadminRouteRouteWithChildren =
  protectedadminRouteRoute._addFileChildren(protectedadminRouteRouteChildren)

interface protectedRouteRouteChildren {
  protectedadminRouteRoute: typeof protectedadminRouteRouteWithChildren
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedadminRouteRoute: protectedadminRouteRouteWithChildren,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface publicauthRouteRouteChildren {
  publicauthForgotPasswordIndexRoute: typeof publicauthForgotPasswordIndexRoute
  publicauthLoginIndexRoute: typeof publicauthLoginIndexRoute
  publicauthSignUpIndexRoute: typeof publicauthSignUpIndexRoute
  publicauthUpdatePasswordIndexRoute: typeof publicauthUpdatePasswordIndexRoute
}

const publicauthRouteRouteChildren: publicauthRouteRouteChildren = {
  publicauthForgotPasswordIndexRoute: publicauthForgotPasswordIndexRoute,
  publicauthLoginIndexRoute: publicauthLoginIndexRoute,
  publicauthSignUpIndexRoute: publicauthSignUpIndexRoute,
  publicauthUpdatePasswordIndexRoute: publicauthUpdatePasswordIndexRoute,
}

const publicauthRouteRouteWithChildren = publicauthRouteRoute._addFileChildren(
  publicauthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  publicauthRouteRoute: publicauthRouteRouteWithChildren,
  publichomeIndexRoute: publichomeIndexRoute,
  publicPollIndexRoute: publicPollIndexRoute,
  publicWhoAreWeIndexRoute: publicWhoAreWeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
