/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PollIndexRouteImport } from './routes/poll/index'
import { Route as homeIndexRouteImport } from './routes/(home)/index'

const PollIndexRoute = PollIndexRouteImport.update({
  id: '/poll/',
  path: '/poll/',
  getParentRoute: () => rootRouteImport,
} as any)
const homeIndexRoute = homeIndexRouteImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof homeIndexRoute
  '/poll/': typeof PollIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof homeIndexRoute
  '/poll': typeof PollIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(home)/': typeof homeIndexRoute
  '/poll/': typeof PollIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/poll/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/poll'
  id: '__root__' | '/(home)/' | '/poll/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  homeIndexRoute: typeof homeIndexRoute
  PollIndexRoute: typeof PollIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/poll/': {
      id: '/poll/'
      path: '/poll'
      fullPath: '/poll/'
      preLoaderRoute: typeof PollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(home)/': {
      id: '/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  homeIndexRoute: homeIndexRoute,
  PollIndexRoute: PollIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
