export const SIDEBAR_STRINGS = {
  title: "בר שכונתי קריית אליעזר",
  subtitle: "קואופרטיב חיפאי",
  home: "דף הבית",
  poll: "סקר שם",
  whoAreWe: "מי אנחנו?",
  hameData: "עריכת דף בית",
  comingSoon: "בקרוב",
  login: "התחבר",
  giveLoan: "לתת הלוואה",
  buyShare: "קניית מניה",
  logout: "התנתק",
  adminPage: "דפי אדמין",
  signUp: "הרשם",
} as const
